- hosts: QA
  sudo: yes
  tasks:
     - yum:
        - name: httpd
          state: installed
       tags:
     - packages

     - service:
             - name: httpd
               state: started
        tags:
     -  service

