- hosts: QA
  sudo: Yes
  tasks:
     - name: Stop httpd service
       action: service name=httpd state=stopped
     - name: Start httpd service
       service:
           name: httpd
           state: started
       notify: service down    
  handlers:
     - name: service down
       service: 
           name: httpd 
           state: stopped

