- hosts: QA
  sudo: yes
  tasks:
     - name: HTTP stop
       command: service httpd stop
       notify: HTTP start
  handlers:
          - name: HTTP start
            command: service httpd start

