- hosts: QA
  sudo: yes
  vars_prompt:
          - name: pkgtoinstall
            prompt: Install which package ?
            default: telnet
            private: no
  tasks:
          - name: install package "{{ pkgtoinstall }}"
            command: echo "{{ pkgtoinstall }}"
